# Generated by Django 4.2.6 on 2023-10-28 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='last_name',
        ),
    ]
