# Generated by Django 4.2.6 on 2023-11-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0003_profession_description_profession_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profession',
            new_name='ProfessionalSpecialization',
        ),
        migrations.AlterModelOptions(
            name='professionalspecialization',
            options={'verbose_name': 'professional_specialization', 'verbose_name_plural': 'professional_specializations'},
        ),
        migrations.RemoveField(
            model_name='professional',
            name='profession',
        ),
        migrations.AddField(
            model_name='professional',
            name='specializations',
            field=models.ManyToManyField(related_name='professionals', to='professional.professionalspecialization'),
        ),
        migrations.AlterModelTable(
            name='professionalspecialization',
            table='professional_specialization',
        ),
    ]
