# Generated by Django 4.2.6 on 2023-11-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0004_rename_profession_professionalspecialization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionalspecialization',
            options={'verbose_name': 'professional specialization', 'verbose_name_plural': 'professional specializations'},
        ),
    ]
